openapi: 3.2.0
info:
  title: Aembit Cloud Credential Provider (Deprecated) API
  version: v1
servers:
- url: https://{tenant}.aembit.io
  variables:
    tenant:
      default: tenant
      description: Aembit Tenant ID
security:
- {}
tags:
- name: Credential Provider (Deprecated)
paths:
  /api/v1/credential-providers/{id}:
    get:
      tags:
      - Credential Provider (Deprecated)
      summary: Get a Credential Provider
      description: Get a Credential Provider identified by its ID.
      operationId: get-credential-provider
      parameters:
      - name: id
        in: path
        description: ID of Credential Provider
        required: true
        schema:
          type: string
          format: uuid
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Credential Provider
          content:
            application/json:
              schema:
                description: Individual Credential Provider
                $ref: '#/components/schemas/CredentialProviderUIDTO'
        '204':
          description: Credential Provider Not Found
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
    delete:
      tags:
      - Credential Provider (Deprecated)
      summary: Delete a Credential Provider
      description: Delete a Credential Provider identified by its ID.
      operationId: delete-credential-provider
      parameters:
      - name: id
        in: path
        description: ID of Credential Provider
        required: true
        schema:
          type: string
          format: uuid
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      responses:
        '204':
          description: Deleted Credential Provider
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
    patch:
      tags:
      - Credential Provider (Deprecated)
      summary: Patch a Credential Provider
      description: Patch a Credential Provider.
      operationId: patch-credential-provider
      parameters:
      - name: id
        in: path
        description: ID of Credential Provider
        required: true
        schema:
          type: string
          format: uuid
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      requestBody:
        description: CredentialProviderPatchDTO
        content:
          application/json:
            schema:
              description: Patch request for an individual Credential Provider
              $ref: '#/components/schemas/CredentialProviderPatchDTO'
      responses:
        '201':
          description: Patched Credential Provider
          content:
            application/json:
              schema:
                description: Individual Credential Provider
                $ref: '#/components/schemas/CredentialProviderUIDTO'
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
  /api/v1/credential-providers/{id}/authorize:
    get:
      tags:
      - Credential Provider (Deprecated)
      summary: Get a Credential Provider Authorization URL
      description: Get a Credential Provider Authorization URL identified by the Credential Provider ID.
      operationId: get-credential-provider-authorization
      parameters:
      - name: id
        in: path
        description: ID of Credential Provider
        required: true
        schema:
          type: string
          format: uuid
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      responses:
        '302':
          description: Redirects to the Credential Provider Authorization URL
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
  /api/v1/credential-providers:
    get:
      tags:
      - Credential Provider (Deprecated)
      summary: Get a page of Credential Providers
      description: Get a page of Credential Providers.
      operationId: get-credential-providers
      parameters:
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      - name: page
        in: query
        schema:
          type: integer
          format: int32
          default: 1
      - name: per-page
        in: query
        schema:
          type: integer
          format: int32
          default: 100
      - name: filter
        in: query
        schema:
          type: string
          default: ''
      - name: order
        in: query
        schema:
          type: string
          default: ''
      - name: group-by
        in: query
        schema:
          type: string
          default: ''
      responses:
        '200':
          description: Page of Credential Providers
          content:
            application/json:
              schema:
                description: Page of Credential Providers
                $ref: '#/components/schemas/CredentialProviderUIDTOCredentialProviderListDTO'
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
    post:
      tags:
      - Credential Provider (Deprecated)
      summary: Create a Credential Provider
      description: Create a Credential Provider.
      operationId: post-credential-provider
      parameters:
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      requestBody:
        description: CredentialProviderDTO
        content:
          application/json:
            schema:
              description: Individual Credential Provider
              $ref: '#/components/schemas/CredentialProviderDTO'
      responses:
        '201':
          description: Created Credential Provider
          content:
            application/json:
              schema:
                description: Individual Credential Provider
                $ref: '#/components/schemas/CredentialProviderUIDTO'
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
    put:
      tags:
      - Credential Provider (Deprecated)
      summary: Update a Credential Provider
      description: Update a Credential Provider.
      operationId: put-credential-provider
      parameters:
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      requestBody:
        description: CredentialProviderDTO
        content:
          application/json:
            schema:
              description: Individual Credential Provider
              $ref: '#/components/schemas/CredentialProviderDTO'
      responses:
        '201':
          description: Updated Credential Provider
          content:
            application/json:
              schema:
                description: Individual Credential Provider
                $ref: '#/components/schemas/CredentialProviderUIDTO'
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
  /api/v1/credential-providers/{id}/verification:
    get:
      tags:
      - Credential Provider (Deprecated)
      summary: Verify the Credential Provider
      description: Verify the Credential Provider will successfully return a credential.
      operationId: get-credential-provider-verification
      parameters:
      - name: id
        in: path
        description: ID of Credential Provider
        required: true
        schema:
          type: string
          format: uuid
      - name: X-Aembit-ResourceSet
        in: header
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Details on the verification of a Credential Provider
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
components:
  schemas:
    CredentialProviderUIDTOCredentialProviderListDTO:
      type: object
      properties:
        page:
          type: integer
          description: Page of entities
          format: int32
        perPage:
          type: integer
          description: Number of entities requested for the current page
          format: int32
        order:
          type:
          - 'null'
          - string
          description: Ordering criteria used for the current page
        statusCode:
          type: integer
          description: HTTP Status Code of the response
          format: int32
        recordsTotal:
          type: integer
          description: Total number of Credential Providers
          format: int32
        credentialProviders:
          type:
          - 'null'
          - array
          items:
            description: Individual Credential Provider
            $ref: '#/components/schemas/CredentialProviderUIDTO'
          description: Page of Credential Providers
      additionalProperties: false
      description: Page of Credential Providers
    CredentialProviderPatchDTO:
      type: object
      properties:
        name:
          maxLength: 128
          type:
          - 'null'
          - string
          description: New Name for the identified entity
        description:
          type:
          - 'null'
          - string
          description: New Description for the identified entity
        isActive:
          type:
          - 'null'
          - boolean
          description: New Status for the identified entity
          format: boolean
        tags:
          type:
          - 'null'
          - array
          items:
            description: Aembit Entity Tag Details
            $ref: '#/components/schemas/TagDTO'
          description: New Tags for the identified entity
        providerDetailJSON:
          type:
          - 'null'
          - string
          description: JSON representation of the Credential Provider configuration details
        type:
          type:
          - 'null'
          - string
          description: Credential Provider Type (e.g. oauth-client-credential, username-password, etc.)
      additionalProperties: false
      description: Patch request for an individual Credential Provider
    GenericResponseDTO:
      type: object
      properties:
        success:
          type: boolean
          description: True if the API call was successful, False otherwise
        message:
          type:
          - 'null'
          - string
          description: Message to indicate why the API call failed
        id:
          type: integer
          description: Unique identifier of the API response
          format: int32
      additionalProperties: false
      description: DTO for a Generic API Response
    TagDTO:
      required:
      - key
      - value
      type: object
      properties:
        key:
          minLength: 1
          type: string
          description: Tag Key
        value:
          minLength: 1
          type: string
          description: Tag Key Value
      additionalProperties: false
      description: Aembit Entity Tag Details
    CredentialProviderDTO:
      required:
      - isActive
      - name
      - resourceSet
      - type
      type: object
      properties:
        externalId:
          type: string
          format: uuid
        name:
          maxLength: 128
          minLength: 1
          type: string
          description: Name of the Entity
        description:
          type:
          - 'null'
          - string
          description: Description of the Entity
        isActive:
          type: boolean
          description: True/False value that determines if this entity is Active or Disabled
          format: boolean
        tags:
          type:
          - 'null'
          - array
          items:
            description: Aembit Entity Tag Details
            $ref: '#/components/schemas/TagDTO'
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type:
          - 'null'
          - string
          format: date-time
        createdBy:
          type:
          - 'null'
          - string
        modifiedBy:
          type:
          - 'null'
          - string
        resourceSet:
          type: string
          description: ID of the Resource Set in which this Access Entity exists
          format: uuid
        type:
          minLength: 1
          type: string
          description: Credential Provider Type (e.g. oauth-client-credential, username-password, etc.)
        roleId:
          type:
          - 'null'
          - string
          description: Credential Provider Role for use with Aembit Access Token type Credential Providers
          format: uuid
        lifetimeTimeSpanSeconds:
          type: integer
          description: The Lifetime of a Credential Provider's credential value
          format: int32
        lifetimeExpiration:
          type:
          - 'null'
          - string
          description: The expiration timestamp for a Credential Provider's credential value
          format: date-time
        providerDetailJSON:
          type:
          - 'null'
          - string
          description: JSON representation of the Credential Provider configuration details
        accessPolicyCount:
          type: integer
          description: Access Policies associated with this Credential Provider
          format: int32
      additionalProperties: false
      description: Individual Credential Provider
    CredentialProviderUIDTO:
      required:
      - isActive
      - name
      - resourceSet
      - type
      type: object
      properties:
        externalId:
          type: string
          format: uuid
        name:
          maxLength: 128
          minLength: 1
          type: string
          description: Name of the Entity
        description:
          type:
          - 'null'
          - string
          description: Description of the Entity
        isActive:
          type: boolean
          description: True/False value that determines if this entity is Active or Disabled
          format: boolean
        tags:
          type:
          - 'null'
          - array
          items:
            description: Aembit Entity Tag Details
            $ref: '#/components/schemas/TagDTO'
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type:
          - 'null'
          - string
          format: date-time
        createdBy:
          type:
          - 'null'
          - string
        modifiedBy:
          type:
          - 'null'
          - string
        resourceSet:
          type: string
          description: ID of the Resource Set in which this Access Entity exists
          format: uuid
        type:
          minLength: 1
          type: string
          description: Credential Provider Type (e.g. oauth-client-credential, username-password, etc.)
        roleId:
          type:
          - 'null'
          - string
          description: Credential Provider Role for use with Aembit Access Token type Credential Providers
          format: uuid
        lifetimeTimeSpanSeconds:
          type: integer
          description: The Lifetime of a Credential Provider's credential value
          format: int32
        lifetimeExpiration:
          type:
          - 'null'
          - string
          description: The expiration timestamp for a Credential Provider's credential value
          format: date-time
        providerDetailJSON:
          type:
          - 'null'
          - string
          description: JSON representation of the Credential Provider configuration details
        accessPolicyCount:
          type: integer
          description: Access Policies associated with this Credential Provider
          format: int32
      additionalProperties: false
      description: Individual Credential Provider
  securitySchemes:
    bearerAuth:
      type: http
      description: Authorization header using the Bearer scheme.
      scheme: bearer
      bearerFormat: Reference
