openapi: 3.2.0
info:
  title: Aembit Cloud SignOn Policy API
  version: v1
servers:
- url: https://{tenant}.aembit.io
  variables:
    tenant:
      default: tenant
      description: Aembit Tenant ID
security:
- {}
tags:
- name: SignOn Policy
paths:
  /api/v1/signin-policies:
    get:
      tags:
      - SignOn Policy
      summary: Get a SignOn Policy
      description: Get a SignOn Policy by its name.
      operationId: get-signon-policy
      responses:
        '200':
          description: SignOn Policy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSignInPolicyDTO'
        '204':
          description: SignOn Policy Not Found
        '400':
          description: Bad Request
        '401':
          description: Not Authenticated
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: DTO for a Generic API Response
                $ref: '#/components/schemas/GenericResponseDTO'
components:
  schemas:
    GetSignInPolicyDTO:
      type: object
      properties:
        ssoRequired:
          type: boolean
        mfaRequired:
          type: boolean
      additionalProperties: false
    GenericResponseDTO:
      type: object
      properties:
        success:
          type: boolean
          description: True if the API call was successful, False otherwise
        message:
          type:
          - 'null'
          - string
          description: Message to indicate why the API call failed
        id:
          type: integer
          description: Unique identifier of the API response
          format: int32
      additionalProperties: false
      description: DTO for a Generic API Response
  securitySchemes:
    bearerAuth:
      type: http
      description: Authorization header using the Bearer scheme.
      scheme: bearer
      bearerFormat: Reference
